---
title: "functions"
---

The collection of functions range from the very simple, cleaning tasks that could be required regularly, to the more complex handicapping functions.  

The four sections below split the functions into groups, but it is more likely that the functions will be used one after another as horse racing data is cleaned and prepared ahead of handicapping.

### Cleaning

Cleaning functions attempt to, surprise, surprise, clean racing data, from racing times, to weight, see the [Data Cleaning](data_cleaning.html) vignette to see a few of them in use.

function | what's it for | help
---------|---------------|-------
conv\_times | converts times in character format (such as "1m39.99") into a time in seconds | [help](conv_times.html)
conv\_margins | converts margins between horses from lengths into seconds | [help](conv_margins.html)
conv\_wgt | converts weights from character format of stones-lbs, or from numeric format from kg to lbs | [help](conv_wgt.html)
conv\_len | converts lengths from character format, such as "1 3/4" or "nse", into numeric format | [help](conv_len.html)

### Preparation

Preparation functions aim to prepare data for either handicapping or further analysis, see the [Data Preparation](data_prep.html) and [zipf\_race](zipf_race.html) vignettes to see a few of these functions in use.

function | what's it for | help
---------|---------------|------
btn\_sec | calculates the margin (in seconds) between horses | [help](btn_sec.html)
fin\_spd | calculates finishing speed percentages using sectionals | [help](fin_spd.html)
fin\_sect | calculates finishing sectionals using finishing speeds | [help](fin_sect.html)
lbs\_per\_sec | lbs per second scale | [help](lbs_per_sec.html)
rnrs\_btn | calculates percentage of runners beaten | [help](rnrs_btn.html)
bha\_ls | returns BHA lengths per second scale | [help](bha_ls.html)

### Handicapping

These functions typically require a number of the functions above to be used, to get data into a format that the functions below can deal with.

function | what's it for | help
---------|---------------|------
diff\_at\_wgts | calculates the difference at the weights | [help](diff_at_wgts.html)
zipf\_race | handicaps a single race using one race | [help](zipf_race.html)
zipf\_hcp | handicaps a single race using many races | [help](zipf_hcp.html)
zipf\_init | initialises a handicap using many races | [help](zipf_init.html)

### Misc

These functions provide assistance for potential tasks.

function | what's it for | help
---------|---------------|-----
theme\_rcapper | a custom ggplot theme | [help](theme_rcapper.html)
mean\_rating | helper function to be used as a parameter in the `boot` function from the **boot** package | [help](mean_rating.html)
merge\_zipf\_init | merges list returned by [zipf_init](zipf_init.html) and the dataframe entered into that function | [help](merge_zipf_init.html)

<a href="https://github.com/durtal/RcappeR" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#d9230f; color:#fcfcfc; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
